categorie_categorie_index:
    path:     /
    defaults: { _controller: "EPIUserBundle:categorie:index" }
    methods:  GET

categorie_categorie_show:
    path:     /{id}/show
    defaults: { _controller: "EPIUserBundle:categorie:show" }
    methods:  GET

categorie_categorie_new:
    path:     /new
    defaults: { _controller: "EPIUserBundle:categorie:new" }
    methods:  [GET, POST]

categorie_categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "EPIUserBundle:categorie:edit" }
    methods:  [GET, POST]

categorie_categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "EPIUserBundle:categorie:delete" }
    methods:  DELETE
