<?php

namespace EPI\UserBundle\Repository;

/**
 * commentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commentairesRepository extends \Doctrine\ORM\EntityRepository
{
}
