<?php

namespace EPI\UserBundle\Repository;

/**
 * demandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeRepository extends \Doctrine\ORM\EntityRepository
{
}
