<?php

namespace EPI\UserBundle\Repository;

/**
 * livresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class livresRepository extends \Doctrine\ORM\EntityRepository
{
}
