<?php

namespace EPI\UserBundle\Repository;

/**
 * messagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class messagesRepository extends \Doctrine\ORM\EntityRepository
{
}
