<?php

namespace EPI\UserBundle\Repository;

/**
 * sous_categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sous_categorieRepository extends \Doctrine\ORM\EntityRepository
{
}
